services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-multipais
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./backend/.env:/app/.env:ro
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
